### ISSUE TITLE
Complete meta-staking queries

### ISSUE THREAD

**Issue by JakeHartnell** [CosmWasm/mesh-security#33]
Implement the unimplemented queries in the `meta-staking` contract:
- [ ] `all_validators`: return all validators that a consumer contract delegates to.
- [ ] `delegation`: return info about a particular consumer delegation
- [ ] `consumers`: return a list of consumers

**Comment by Art3miX** [comment]
quick question, `all_validators` and `consumers` should be paginated? So it should also accept optional start and limit?

**Comment by JakeHartnell** [comment]
> quick question, `all_validators` and `consumers` should be paginated? So it should also accept optional start and limit?

Sure, why not? Go ahead and make them paginated if you want. Would make the default limit pretty high though.

**Comment by JakeHartnell** [comment]
Closed with #39.
